### ISSUE TITLE
库有些问题

### ISSUE THREAD

**Issue by nlnkjb** [weiguangzhao/DF_MVR#2]
lib文件夹下没有requirement文件

**Comment by weiguangzhao** [comment]
Thanks for your attention. We have updated the commit and added the requirement.txt, you can refresh the page and download it.

**Comment by nlnkjb** [comment]
您好，打扰了，我按readme配置环境时，很多库的版本之间或者和python3.8.10都不兼容，比如pytorch3d和python的版本就会报错，请您能提供一下详细点的库版本吗

**Comment by weiguangzhao** [comment]
The following is the detailed version of DFMVR package. "conda.txt" stands for the conda config, and "pip.txt" is for the pip config.
[conda.txt](https://github.com/weiguangzhao/DF_MVR/files/14432777/conda.txt)
[pip.txt](https://github.com/weiguangzhao/DF_MVR/files/14432779/pip.txt)

**Comment by nlnkjb** [comment]
非常抱歉再次打扰您，我在运行test_simple.py文件时报错Segmentation fault (core dumped)，使用-X faulthandler查看后最终指向mtcnn这个库，我尝试了degug,代码在from dataset.pixel_face.dataset_preprocess import get_face_mask时停止运行，如果将这行注释，会在下面调用到get_face_mask函数时才停止运行，不注释，在这行时就停止运行了，库版本我已经严格按照您之前提供的版本，想咨询您一下之前遇到过这个问题吗，不胜感激

**Comment by weiguangzhao** [comment]
Hi, you can try to modify the version of mtcnn. I haven't encountered this situation before. I guess there may be two situations: 1）The mtcnn version is incompatible with your current environment. 2）Not being able to find the file path may also cause this error.
