### ISSUE TITLE
Encounter many conflicts

### ISSUE THREAD

**Issue by mumucc1** [weiguangzhao/DF_MVR#4]
When I was configuring the environment and following the package versions provided by the author, I encountered many conflicts. How can I resolve them?

**Comment by weiguangzhao** [comment]
Hi, thanks for your attention. The enviroment config we provided is based on RTX3090.  If you are adopting other GPU card, you need to change the version of package. 
The following is our detailed version of DFMVR package based on RTX3090. "conda.txt" stands for the conda config, and "pip.txt" is for the pip config.  Hope it helps.
[pip.txt](https://github.com/weiguangzhao/DF_MVR/files/14805654/pip.txt)
[conda.txt](https://github.com/weiguangzhao/DF_MVR/files/14805657/conda.txt)

**Comment by mumucc1** [comment]
> Hi, thanks for your attention. The enviroment config we provided is based on RTX3090. If you are adopting other GPU card, you need to change the version of package.
> The following is our detailed version of DFMVR package based on RTX3090. "conda.txt" stands for the conda config, and "pip.txt" is for the pip config. Hope it helps.
> [pip.txt](https://github.com/weiguangzhao/DF_MVR/files/14805654/pip.txt)
> [conda.txt](https://github.com/weiguangzhao/DF_MVR/files/14805657/conda.txt)

Thanks！I succeeded in test and train.And then,i have another questions:1、the email on the pixel-face dataset is invalid
2、the obj outcome of the test_sample.py is gray, 
![Uploading 截屏2024-04-01 13.58.51.png…]()
how can I put the colorful texture on the 3D mesh? 
Thanks very much!

**Comment by weiguangzhao** [comment]
Hi, mumucc1.
1.  For pixel-face dataset, you can try to contact the first author of the pixelface paper directly. Moreover,  Multi-PIE is the alternative dataset.
2. Our method mainly focuses on the reconstruction of shapes, which can be seen based on RMSE metrics. But we also provide the 3DMM color as the reference. You can uncomment the Line40 in the test_pixel_face.py to get the predicted 3DMM Mesh color.

**Comment by mumucc1** [comment]
> Hi, mumucc1.
> 
> 1. For pixel-face dataset, you can try to contact the first author of the pixelface paper directly. Moreover,  Multi-PIE is the alternative dataset.
> 2. Our method mainly focuses on the reconstruction of shapes, which can be seen based on RMSE metrics. But we also provide the 3DMM color as the reference. You can uncomment the Line40 in the test_pixel_face.py to get the predicted 3DMM Mesh color.
Thank you for your patient guidance! So, to obtain a colored mesh, I must use test_pixel_face.py, correct? If I don't have this dataset, then I could use Multi-PIE to achieve the same effect. Additionally, I noticed that Line 30 of test_sample.py also involves color rendering. Why does the outputted obj from test_sample.py lack color?

**Comment by weiguangzhao** [comment]
Hi, mumucc1.
 1.So, to obtain a colored mesh, I must use test_pixel_face.py, correct? 
  ------->No, you can add the  Line40 of the test_pixel_face.py to the  Line 30 of test_sample.py.  
 2. If I don't have this dataset, then I could use Multi-PIE to achieve the same effect. 
 -------> Actually, Multi-PIE achieves the better performance than Pixel-face. Since MultiPIE contain numerous light environments, photography angles and object samples from different countries.

**Comment by mumucc1** [comment]
> Hi, mumucc1.
> 1.So, to obtain a colored mesh, I must use test_pixel_face.py, correct?
> ------->No, you can add the Line40 of the test_pixel_face.py to the Line 30 of test_sample.py.
> 2. If I don't have this dataset, then I could use Multi-PIE to achieve the same effect.
> -------> Actually, Multi-PIE achieves the better performance than Pixel-face. Since MultiPIE contain numerous light environments, photography angles and object samples from different countries.

I modified the test_sample.py file as you suggested and tried to run it, but the resulting obj file is still gray. Is it possible that other texture or color related files were not saved?
<img width="804" alt="show" src="https://github.com/weiguangzhao/DF_MVR/assets/162797696/063d2835-a360-415a-b104-27879a2fad5e">

**Comment by weiguangzhao** [comment]
Hi mumucc1, please check if it is an issue with your visualization software. It works normally for me. For the visualization software, Meshlab and CloudCompare is the preferred.
![1711955692(1)](https://github.com/weiguangzhao/DF_MVR/assets/22412975/1cb6e2c2-df67-42d4-8f8b-f9d78e74ec6b)
![1711955870(1)](https://github.com/weiguangzhao/DF_MVR/assets/22412975/e237f7c7-c722-4ee6-b24f-9092c1cf3952)

**Comment by mumucc1** [comment]
> Hi mumucc1, please check if it is an issue with your visualization software. It works normally for me. For the visualization software, Meshlab and CloudCompare is the preferred.
> ![1711955692(1)](https://private-user-images.githubusercontent.com/22412975/318364918-1cb6e2c2-df67-42d4-8f8b-f9d78e74ec6b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTg1NjEsIm5iZiI6MTcxMTk1ODI2MSwicGF0aCI6Ii8yMjQxMjk3NS8zMTgzNjQ5MTgtMWNiNmUyYzItZGY2Ny00MmQ0LThmOGItZjlkNzhlNzRlYzZiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA3NTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlMDhkYmIzYzJlZTRhOTI4NjFmNmY5NjYxODc1ZmM0ZGI2NThjZmQzZDI5M2M5YjBlMzU3OTA1YTUxMGE3YzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1ZguONqjkP5r9Hv3GZjvRK8w1lbiqEJEUr-gFlXJVNA)
> ![1711955870(1)](https://private-user-images.githubusercontent.com/22412975/318365611-e237f7c7-c722-4ee6-b24f-9092c1cf3952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTg1NjEsIm5iZiI6MTcxMTk1ODI2MSwicGF0aCI6Ii8yMjQxMjk3NS8zMTgzNjU2MTEtZTIzN2Y3YzctYzcyMi00ZWU2LWIyNGYtOTA5MmMxY2YzOTUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA3NTc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxYmNiYzllNDhhMmU3YjQ2ZDFmOWI0NmYwNzJiNDE0YmUyMzA0ZDJjYzRiMmZmMTk5NDRmM2FlMjBkNDQzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IJd6lu6EctIPBODq1Tn4D4biavvKRVdgc6IbZHDfPII)

Ah ha! Thank you for your guidance; with your help, I have successfully seen the colored 3D mesh. I found that the issue was with my MeshLab settings, not the code itself. Thank you again for your guidance and your work!
![Uploading Thanks.png…]()

**Comment by mumucc1** [comment]
Ah ha! Thank you for your guidance; with your help, I have successfully seen the colored 3D mesh. I found that the issue was with my MeshLab settings, not the code itself. Thank you again for your guidance and your work!
<img width="467" alt="Thanks" src="https://github.com/weiguangzhao/DF_MVR/assets/162797696/030cd1f2-ed66-4909-8c6e-02558af8cb76">

**Comment by Bparmaksiz** [comment]
Unfortunately I'm facing same issue, packages conflicts!
I'm not sure what is wrong but tensorflow=2.5 and numpy=1.20 have some trouble.
Even though using same environment file it is interesting to have trouble, so in this case i doubt about Operating system. would you tell me what OS do you run this repo? Ubuntu 22.04?
BR Thanks

**Comment by weiguangzhao** [comment]
> Unfortunately I'm facing same issue, packages conflicts! I'm not sure what is wrong but tensorflow=2.5 and numpy=1.20 have some trouble. Even though using same environment file it is interesting to have trouble, so in this case i doubt about Operating system. would you tell me what OS do you run this repo? Ubuntu 22.04? BR Thanks

Thanks for your attention, we run the repo on Ubuntu 20.04.2 LTS.

**Comment by Bparmaksiz** [comment]
> > Unfortunately I'm facing same issue, packages conflicts! I'm not sure what is wrong but tensorflow=2.5 and numpy=1.20 have some trouble. Even though using same environment file it is interesting to have trouble, so in this case i doubt about Operating system. would you tell me what OS do you run this repo? Ubuntu 22.04? BR Thanks
> 
> Thanks for your attention, we run the repo on Ubuntu 20.04.2 LTS.

Thank you for quick responce! Maybe that would be better if you clarify your anaconda version and pip version.
Thanks again!

**Comment by weiguangzhao** [comment]
> > > Unfortunately I'm facing same issue, packages conflicts! I'm not sure what is wrong but tensorflow=2.5 and numpy=1.20 have some trouble. Even though using same environment file it is interesting to have trouble, so in this case i doubt about Operating system. would you tell me what OS do you run this repo? Ubuntu 22.04? BR Thanks
> > 
> > 
> > Thanks for your attention, we run the repo on Ubuntu 20.04.2 LTS.
> 
> Thank you for quick responce! Maybe that would be better if you clarify your anaconda version and pip version. Thanks again!

The following is our detailed version of DFMVR package based on RTX3090. "conda.txt" stands for the conda config, and "pip.txt" is for the pip config. Hope it helps. By the way,  the version of  conda is  4.9.2 and pip is 20.2.4

[conda.txt](https://github.com/weiguangzhao/DF_MVR/files/15433568/conda.txt)
[pip.txt](https://github.com/weiguangzhao/DF_MVR/files/15433569/pip.txt)
