### ISSUE TITLE
Albedo Map

### ISSUE THREAD

**Issue by lalall1** [weiguangzhao/DF_MVR#5]
Hello, I've noticed that the rendered mesh from the obj results of test_sample lacks strong realistic textures, and it seems like everyone's skin tone is almost the same. Could this be due to the absence of an albedo map? Does 3DMM offer an albedo map effect similar to that of DECA?
Thanks！
<img width="317" alt="截屏2024-04-02 14 44 42" src="https://github.com/weiguangzhao/DF_MVR/assets/165761414/c784544f-cc54-4651-bebd-fca1e60b23cd">

**Comment by weiguangzhao** [comment]
Hi lalall1, thanks for your attention. Our work mainly focuses on the reconstruction of 3D shapes, so we do not pay too much attention to textures. But I think the main reason is that the facial skin color and ambient light provided by pixelface data are similar.  If you use Multi-PIE training, the effectiveness of skin color change will be much better. 
Furthermore, 3DMM only provides color collections and does not provide albedo maps.  Regarding 3DMM texture enhancement, I can recommend an article to you: Towards High-Fidelity 3D Face Reconstruction from In-the-Wild Images Using Graph Convolutional Networks

**Comment by lalall1** [comment]
> Hi lalall1, thanks for your attention. Our work mainly focuses on the reconstruction of 3D shapes, so we do not pay too much attention to textures. But I think the main reason is that the facial skin color and ambient light provided by pixelface data are similar. If you use Multi-PIE training, the effectiveness of skin color change will be much better.
> Furthermore, 3DMM only provides color collections and does not provide albedo maps. Regarding 3DMM texture enhancement, I can recommend an article to you: Towards High-Fidelity 3D Face Reconstruction from In-the-Wild Images Using Graph Convolutional Networks
Hello!Thank you for your patient answers！Are you saying that you haven't done any rendering of lighting and other environmental effects (or if you have, I didn't see it)?  Would this lead to significant errors when calculating image loss? Because I've seen other 3DMM-related work that includes rendering of lighting and such, which makes the skin color appear more realistic.
Thank you !

**Comment by weiguangzhao** [comment]
Hi lalall1. It's kindly to note that the images you presented are OBJ files, and the point light source for the 3D models is set using visualization software. If the point light source is placed too close, it will result in all faces appearing overly bright. To provide a proper comparison, you can render the 3D objects into 2D using the predicted point light source positions from our network. Alternatively, you also can directly visualize the rendered images predicted by our model (Line81-83 DF_MVR/network/MVRnet.py).

While we do not emphasize texture, it is not entirely disregarded. If you aim to enhance texture, you may consider increasing the weight of the photo loss, gamma loss and reflect loss (Line199 DF_MVR/network/MVRnet.py).

At last. Our framework incorporates considerations for lighting and environmental effects. Firstly, we utilize masks to remove non-facial parts effect. Secondly, the photo loss  gamma loss and reflect loss enables learning of pixel color variations.  Additionally, this pre-trained model is solely trained on the pixel face dataset, which has limited number of sampls and lighting variations. So, if you want to achieve better texture results, we recommend training with a larger and more diverse dataset based on our network.

**Comment by lalall1** [comment]
> Hi lalall1. It's kindly to note that the images you presented are OBJ files, and the point light source for the 3D models is set using visualization software. If the point light source is placed too close, it will result in all faces appearing overly bright. To provide a proper comparison, you can render the 3D objects into 2D using the predicted point light source positions from our network. Alternatively, you also can directly visualize the rendered images predicted by our model (Line81-83 DF_MVR/network/MVRnet.py).
> 
> While we do not emphasize texture, it is not entirely disregarded. If you aim to enhance texture, you may consider increasing the weight of the photo loss, gamma loss and reflect loss (Line199 DF_MVR/network/MVRnet.py).
> 
> At last. Our framework incorporates considerations for lighting and environmental effects. Firstly, we utilize masks to remove non-facial parts effect. Secondly, the photo loss gamma loss and reflect loss enables learning of pixel color variations. Additionally, this pre-trained model is solely trained on the pixel face dataset, which has limited number of sampls and lighting variations. So, if you want to achieve better texture results, we recommend training with a larger and more diverse dataset based on our network.

Hi,I roughly understand now. Thank you for your patient answer!
