### ISSUE TITLE
文件请求

### ISSUE THREAD

**Issue by nlnkjb** [weiguangzhao/DF_MVR#6]
您好，能提供一份nicp_106_pts.txt文件的例子嘛，我想在facescape数据集上训练尝试一下，看看能否自己根据真值生成地标

**Comment by weiguangzhao** [comment]
你把DF_MVR/network/MVRnet.py的第191行的kp_3d_pred变量保存下来就是我们预测的nicp_106_pts.txt了。（我们删除了5个点只保留了101个点，因为那5个点在外轮廓 我们对比的方法都删除了外轮廓）

还是说你想要一个只用nicp_106_pts.txt训练的例子 我没太理解？

**Comment by nlnkjb** [comment]
我理解错了，我在尝试使用别的数据集进行训练，在数据集的结构上出点问题，以为这个地标真值是像素数据集附带的，感谢回答

**Comment by weiguangzhao** [comment]
训练的时候 GroundTruth 3D landmarks是数据集自带的
