### ISSUE TITLE
Questions about texture sampling

### ISSUE THREAD

**Issue by nlnkjb** [weiguangzhao/DF_MVR#9]
Hello, I paid attention to the texture sampling process pointed out in your paper. I did not see this link in the code. Can you tell me where this step is. I see that the generated meshes are only untextured and 3DMM textured.

**Comment by weiguangzhao** [comment]
Hi, thanks for your attention. Given that the technique of directly sampling textures from original images remains underdeveloped, all visualizations in our paper are based on textures derived from 3D Morphable Models (3DMM). Although textures are not included in the evaluation metrics, we are happy to provide the sample code for texture sampling here as a reference for the community. Notably, the sample code we provide focuses on texture sampling from the frontal view. For more comprehensive results, you might consider implementing weighted sampling from multiple views. The sampling results are stored in the variable ”vertices_img_color“.

Please download the sample code from the below link:
[texture_sampling.txt](https://github.com/user-attachments/files/18221897/texture_sampling.txt)

**Comment by nlnkjb** [comment]
Thank you very much for your reply, and once again, can you provide the calculation code of the indicator RMSE in our paper, I have made a small improvement attempt on the basis of your project, I want to calculate it, but I don't know the specific calculation process, thank you.





山兮木ξ
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "weiguangzhao/DF_MVR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月22日(星期天) 晚上8:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [weiguangzhao/DF_MVR] Questions about texture sampling (Issue #9)





 
Hi, thanks for your attention. Given that the technique of directly sampling textures from original images remains underdeveloped, all visualizations in our paper are based on textures derived from 3D Morphable Models (3DMM). Although textures are not included in the evaluation metrics, we are happy to provide the sample code for texture sampling here as a reference for the community. Notably, the sample code we provide focuses on texture sampling from the frontal view. For more comprehensive results, you might consider implementing weighted sampling from multiple views.
 
Please download the sample code from the below link:
 texture_sampling.txt

**Comment by weiguangzhao** [comment]
The RMSE evaluation code has been provided in  "lib/now_evaluation/compute_error.py". 
We adhere to the standard evaluation protocol, as detailed in https://github.com/soubhiksanyal/now_evaluation.
